// <auto-generated />
using System;
using IgrejaSocial.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IgrejaSocial.Infrastructure.Migrations
{
    [DbContext(typeof(IgrejaSocialDbContext))]
    [Migration("20260130201616_MigracaoInicialFinal")]
    partial class MigracaoInicialFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.Equipamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPatrimonio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservacoesInternas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPatrimonio")
                        .IsUnique();

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DocumentacaoApresentada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RgResponsavel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoResponsavel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RendaFamiliarTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Residencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CpfResponsavel")
                        .IsUnique();

                    b.HasIndex("RgResponsavel");

                    b.ToTable("Familias");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.MembroFamilia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelEscolar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Parentesco")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiDeficiencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RendaIndividual")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SituacaoTrabalho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.RegistroAtendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDevolucaoReal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPrevistaDevolucao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EquipamentoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioEntrega")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoAtendimento")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("RegistrosAtendimento");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.MembroFamilia", b =>
                {
                    b.HasOne("IgrejaSocial.Domain.Entities.Familia", "Familia")
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.RegistroAtendimento", b =>
                {
                    b.HasOne("IgrejaSocial.Domain.Entities.Equipamento", "Equipamento")
                        .WithMany()
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IgrejaSocial.Domain.Entities.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("IgrejaSocial.Domain.Entities.Familia", b =>
                {
                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
